apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: drone-telemetry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
        - name: frontend
          image: capstone-frontend:1.0.0
          ports:
            - containerPort: 3000
          env:
            - name: NEXT_PUBLIC_BACKEND_URL
              value: "http://localhost:8000"
            - name: NEXT_PUBLIC_WS_URL
              value: "ws://localhost:8000/ws"
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: drone-telemetry
spec:
  selector:
    app: frontend
  ports:
    - port: 3000
