apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: drone-telemetry
spec:
  replicas: 2
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: capstone-backend:1.0.0
          command: ["python", "worker.py"]
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: url
            - name: RABBITMQ_URL
              value: "amqp://guest:guest@rabbitmq:5672/"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
