apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: drone-telemetry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: defensetech/gateway:latest
          env:
            - name: BACKEND_URL
              value: "http://backend:8000"
